python model_fusion.py \
    --emotion2vec_dir /home/wangchenhao/Github/baseline/emotion2vec_features \
    --hubert_dir /home/wangchenhao/Github/baseline/hubert_features \
    --csv_path /home/wangchenhao/Github/baseline/csv_files/MSP_Podcast.csv \
    --batch_size 32 \
    --lr 1e-4 \
    --save_dir ./models \
    --patience 15 \
    --seed 20 \
    --min_delta 0.01 \
    --vad_weight 1.0 \
    --emotion_weight 1.0 \
    --cl_weight 0.1 \
    --use_hdgf \
    --use_cl \
    --fusion_dim 768 \
    --temperature 0.07 \
    --num_workers 4